source = ~/.config/assets/palette/palette.conf

monitor=HDMI-A-1,1920x1080@143.98,2560x0,1

monitor=DP-1,2560x1080@60,0x0,1

monitor=DVI-D-1,1920x1080@60,4480x0,1


# Fallback
monitor=,preferred,auto,1

# Samsung
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1

# AOC
workspace = 7, monitor:DVI-D-1
workspace = 8, monitor:DVI-D-1

# LG
workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-1

###############################################

source = style.conf
#source = cleanstlyle.conf
#source = nonoise.conf

#source = ~/.config/hypr/modules/animations/test.conf 
source = ~/.config/hypr/modules/animations/default.conf
#source = ~/.config/hypr/modules/animations/clean.conf

source = programs.conf
source = input.conf
source = keys.conf
source = windows.conf
source = plugins.conf
source = wallpaper.conf

env = HYPRCURSOR_THEME,Adwaita
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
misc:allow_session_lock_restore = 1

