
$HYPRSCRIPT=$HOME/.config/hypr/scripts

$wallpaper = waypaper
$terminal = kitty
$browser = brave
$files = nautilus
$editor = tor-browser
$zoom = woomer
$music = spotify	
$bar = waybar
$menu = rofi
$menu_apps = $menu -show drun 
$menu_cmd = $menu -show run
$colorPicker = hyprpicker -a -fhex
$takeScreenshot = hyprshot --mode=region --freeze --output-folder=Media/Screenshots
$nextKbdLayout = hyprctl switchxkblayout logitech-usb-receiver-keyboard next
$startTimer = $HYPRSCRIPT/timer
$pickEmoji = $menu -show emoji
$toggleDebugOverlay = $HYPRSCRIPT/toggle_debug_overlay
$activateMenu = killall $menu || $menu -show combi
$toggleBar = killall -SIGUSR1 $bar

exec-once = $bar

exec-once = sudo systemctl start bluetooth
exec-once = hyprpm reload
exec-once = waycorner
exec-once = udiskie
exec-once = dunst
exec-once = hypridle
exec-once = nm-applet
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprsunset -t 4000
exec-once = waypaper
